version: "2"

services:
  traefik:
    image: traefik:$VERSION
    container_name: traefik
    hostname: traefik
    volumes:
      - $HOME/.traefik/traefik.toml:/etc/traefik/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 8080:8080
    restart: always
    network_mode: "host"
